# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = linux_wireless
SUB_SRC_FILES = \
    glossary.xml \
    preface.xml \
    ch01_network.xml \
    ch02_wireless_lan.xml \
    ch03_80211_wireless_lan.xml \
    ch04_linux_network.xml \
    ch05_linux_wireless_lan_80211.xml \
    ch06_iwmc3200wifi_analysis.xml \
    reference.xml \

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk